// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySach.Models;

#nullable disable

namespace QuanLySach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828181440_AddDiscountPercentToBook")]
    partial class AddDiscountPercentToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySach.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("QuanLySach.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên",
                            PasswordHash = "rdR9hYaiWTE0Fnf032xkoZDG3BRpiIjdtjWgwypnuYE=",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("QuanLySach.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Французский писатель и лётчик.",
                            Name = "Антуан де Сент-Экзюпери"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Английский писатель и публицист.",
                            Name = "Джордж Оруэлл"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Русский писатель, классик мировой литературы.",
                            Name = "Лев Толстой"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Русский писатель, мыслитель, философ.",
                            Name = "Фёдор Достоевский"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Антуан де Сент-Экзюпери",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3441),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 450m,
                            Stock = 0,
                            Title = "Маленький принц"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джордж Оруэлл",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3460),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 550m,
                            Stock = 0,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джейн Остин",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3461),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 600m,
                            Stock = 0,
                            Title = "Гордость и предубеждение"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Михаил Шолохов",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143105466-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3462),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 700m,
                            Stock = 0,
                            Title = "Тихий Дон"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Михаил Булгаков",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141180144-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3464),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 650m,
                            Stock = 0,
                            Title = "Мастер и Маргарита"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Дж. К. Роулинг",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3465),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 500m,
                            Stock = 0,
                            Title = "Гарри Поттер и Философский камень"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143058144-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3466),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 620m,
                            Stock = 0,
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Лев Толстой",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781400079988-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3467),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 750m,
                            Stock = 0,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Лев Толстой",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3468),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 680m,
                            Stock = 0,
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Александр Дюма",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780140440737-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3469),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 520m,
                            Stock = 0,
                            Title = "Три мушкетёра"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Александр Дюма",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3471),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 580m,
                            Stock = 0,
                            Title = "Граф Монте-Кристо"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Артур Конан Дойл",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3472),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 490m,
                            Stock = 0,
                            Title = "Шерлок Холмс"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Фрэнк Герберт",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3473),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 720m,
                            Stock = 0,
                            Title = "Дюна"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Дуглас Адамс",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3474),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 430m,
                            Stock = 0,
                            Title = "Автостопом по Галактике"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Айзек Азимов",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3475),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 560m,
                            Stock = 0,
                            Title = "Основание"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Дж. Р. Р. Толкин",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3476),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 800m,
                            Stock = 0,
                            Title = "Властелин колец"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Уильям Шекспир",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743477116-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3477),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 380m,
                            Stock = 0,
                            Title = "Ромео и Джульетта"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Шарлотта Бронте",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3479),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 540m,
                            Stock = 0,
                            Title = "Джейн Эйр"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Маргарет Митчелл",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781416548898-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3480),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 670m,
                            Stock = 0,
                            Title = "Унесённые ветром"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Льюис Кэрролл",
                            CategoryId = 5,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3481),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 350m,
                            Stock = 0,
                            Title = "Алиса в стране чудес"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Алан Милн",
                            CategoryId = 5,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/10/WinniePooh.png",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3482),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 320m,
                            Stock = 0,
                            Title = "Винни-Пух"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Памела Трэверс",
                            CategoryId = 5,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780152058104-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3483),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 400m,
                            Stock = 0,
                            Title = "Мэри Поппинс"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Наполеон Хилл",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3485),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 480m,
                            Stock = 0,
                            Title = "Думай и богатей"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Роберт Кийосаки",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3518),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 510m,
                            Stock = 0,
                            Title = "Богатый папа, бедный папа"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Стивен Кови",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3519),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 590m,
                            Stock = 0,
                            Title = "7 навыков высокоэффективных людей"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Стивен Хокинг",
                            CategoryId = 8,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3520),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 620m,
                            Stock = 0,
                            Title = "Краткая история времени"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Юваль Ной Харари",
                            CategoryId = 7,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3521),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 650m,
                            Stock = 0,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Юваль Ной Харари",
                            CategoryId = 7,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3523),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 630m,
                            Stock = 0,
                            Title = "Homo Deus"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Роберт Чалдини",
                            CategoryId = 9,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780061241895-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3524),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = true,
                            Price = 550m,
                            Stock = 0,
                            Title = "Психология влияния"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Даниэль Канеман",
                            CategoryId = 9,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3525),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 580m,
                            Stock = 0,
                            Title = "Думай медленно, решай быстро"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Александр Пушкин",
                            CategoryId = 10,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780192840196-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3526),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 390m,
                            Stock = 0,
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Николай Гоголь",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780300060218-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3527),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 460m,
                            Stock = 0,
                            Title = "Мёртвые души"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780375702242-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3528),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 590m,
                            Stock = 0,
                            Title = "Идиот"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3530),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 710m,
                            Stock = 0,
                            Title = "Братья Карамазовы"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Аркадий и Борис Стругацкие",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781613743416-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3531),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 470m,
                            Stock = 0,
                            Title = "Пикник на обочине"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Станислав Лем",
                            CategoryId = 3,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/0e/Solaris_cover.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3532),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 500m,
                            Stock = 0,
                            Title = "Солярис"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Дж. Д. Сэлинджер",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3533),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 430m,
                            Stock = 0,
                            Title = "Над пропастью во ржи"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Фрэнсис Скотт Фицджеральд",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3534),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 480m,
                            Stock = 0,
                            Title = "Великий Гэтсби"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Олдос Хаксли",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3536),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 520m,
                            Stock = 0,
                            Title = "О дивный новый мир"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Рэй Брэдбери",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
                            CreatedDate = new DateTime(2026, 8, 29, 1, 14, 39, 778, DateTimeKind.Local).AddTicks(3537),
                            DiscountPercent = 0,
                            IsNew = false,
                            IsPopular = false,
                            Price = 490m,
                            Stock = 0,
                            Title = "451 градус по Фаренгейту"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Художественная литература"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Детективы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Детская литература"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Бизнес и саморазвитие"
                        },
                        new
                        {
                            Id = 7,
                            Name = "История"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Наука и техника"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Психология"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Кулинария"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReplyRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("QuanLySach.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmedByAdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuanLySach.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QuanLySach.Models.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentCards");
                });

            modelBuilder.Entity("QuanLySach.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME10",
                            Description = "Скидка для новых покупателей",
                            DiscountPercent = 10,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SUMMER25",
                            Description = "Летняя распродажа",
                            DiscountPercent = 25,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Москва, Россия",
                            Name = "Эксмо"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Москва, Россия",
                            Name = "АСТ"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Санкт-Петербург, Россия",
                            Name = "Азбука"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vai trò siêu quản trị — toàn quyền trên mọi module",
                            IsSuperAdmin = true,
                            Name = "Администратор"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("QuanLySach.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsPerPage")
                        .HasColumnType("int");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultCurrency = "RUB",
                            FacebookUrl = "",
                            FooterText = "© 2026 Книжный Рай. Tất cả các quyền được bảo lưu.",
                            InstagramUrl = "",
                            ItemsPerPage = 12,
                            MaintenanceMessage = "Trang web đang bảo trì, vui lòng quay lại sau.",
                            MaintenanceMode = false,
                            StoreAddress = "",
                            StoreEmail = "info@knizhnyray.com",
                            StoreName = "Книжный Рай",
                            StorePhone = "",
                            TelegramUrl = "",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowCyrillic")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowTransliteration")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLySach.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("QuanLySach.Models.Admin", b =>
                {
                    b.HasOne("QuanLySach.Models.Role", "Role")
                        .WithMany("Admins")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.HasOne("QuanLySach.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QuanLySach.Models.OrderItem", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySach.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuanLySach.Models.PaymentCard", b =>
                {
                    b.HasOne("QuanLySach.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLySach.Models.RolePermission", b =>
                {
                    b.HasOne("QuanLySach.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLySach.Models.Wishlist", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QuanLySach.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuanLySach.Models.Role", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
