// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySach.Models;

#nullable disable

namespace QuanLySach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605020512_AddPaymentCards")]
    partial class AddPaymentCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySach.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Антуан де Сент-Экзюпери",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 450m,
                            Title = "Маленький принц"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джордж Оруэлл",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 550m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джейн Остин",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 600m,
                            Title = "Гордость и предубеждение"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Михаил Шолохов",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143105466-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 700m,
                            Title = "Тихий Дон"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Михаил Булгаков",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141180144-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 650m,
                            Title = "Мастер и Маргарита"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Дж. К. Роулинг",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 500m,
                            Title = "Гарри Поттер и Философский камень"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143058144-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 620m,
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Лев Толстой",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781400079988-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 750m,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Лев Толстой",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 680m,
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Александр Дюма",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780140440737-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 520m,
                            Title = "Три мушкетёра"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Александр Дюма",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 580m,
                            Title = "Граф Монте-Кристо"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Артур Конан Дойл",
                            CategoryId = 2,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 490m,
                            Title = "Шерлок Холмс"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Фрэнк Герберт",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 720m,
                            Title = "Дюна"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Дуглас Адамс",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 430m,
                            Title = "Автостопом по Галактике"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Айзек Азимов",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 560m,
                            Title = "Основание"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Дж. Р. Р. Толкин",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 800m,
                            Title = "Властелин колец"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Уильям Шекспир",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743477116-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 380m,
                            Title = "Ромео и Джульетта"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Шарлотта Бронте",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 540m,
                            Title = "Джейн Эйр"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Маргарет Митчелл",
                            CategoryId = 4,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781416548898-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 670m,
                            Title = "Унесённые ветром"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Льюис Кэрролл",
                            CategoryId = 5,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 350m,
                            Title = "Алиса в стране чудес"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Алан Милн",
                            CategoryId = 5,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/10/WinniePooh.png",
                            IsNew = false,
                            IsPopular = false,
                            Price = 320m,
                            Title = "Винни-Пух"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Памела Трэверс",
                            CategoryId = 5,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780152058104-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 400m,
                            Title = "Мэри Поппинс"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Наполеон Хилл",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 480m,
                            Title = "Думай и богатей"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Роберт Кийосаки",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 510m,
                            Title = "Богатый папа, бедный папа"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Стивен Кови",
                            CategoryId = 6,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 590m,
                            Title = "7 навыков высокоэффективных людей"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Стивен Хокинг",
                            CategoryId = 8,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 620m,
                            Title = "Краткая история времени"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Юваль Ной Харари",
                            CategoryId = 7,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 650m,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Юваль Ной Харари",
                            CategoryId = 7,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 630m,
                            Title = "Homo Deus"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Роберт Чалдини",
                            CategoryId = 9,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780061241895-L.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 550m,
                            Title = "Психология влияния"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Даниэль Канеман",
                            CategoryId = 9,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 580m,
                            Title = "Думай медленно, решай быстро"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Александр Пушкин",
                            CategoryId = 10,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780192840196-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 390m,
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Николай Гоголь",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780300060218-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 460m,
                            Title = "Мёртвые души"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780375702242-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 590m,
                            Title = "Идиот"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Фёдор Достоевский",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 710m,
                            Title = "Братья Карамазовы"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Аркадий и Борис Стругацкие",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781613743416-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 470m,
                            Title = "Пикник на обочине"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Станислав Лем",
                            CategoryId = 3,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/0e/Solaris_cover.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 500m,
                            Title = "Солярис"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Дж. Д. Сэлинджер",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 430m,
                            Title = "Над пропастью во ржи"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Фрэнсис Скотт Фицджеральд",
                            CategoryId = 1,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 480m,
                            Title = "Великий Гэтсби"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Олдос Хаксли",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 520m,
                            Title = "О дивный новый мир"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Рэй Брэдбери",
                            CategoryId = 3,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
                            IsNew = false,
                            IsPopular = false,
                            Price = 490m,
                            Title = "451 градус по Фаренгейту"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Художественная литература"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Детективы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Детская литература"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Бизнес и саморазвитие"
                        },
                        new
                        {
                            Id = 7,
                            Name = "История"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Наука и техника"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Психология"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Кулинария"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuanLySach.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QuanLySach.Models.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentCards");
                });

            modelBuilder.Entity("QuanLySach.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLySach.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.HasOne("QuanLySach.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QuanLySach.Models.OrderItem", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySach.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuanLySach.Models.PaymentCard", b =>
                {
                    b.HasOne("QuanLySach.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLySach.Models.Wishlist", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QuanLySach.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
