// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySach.Models;

#nullable disable

namespace QuanLySach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603061744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySach.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Антуан де Сент-Экзюпери",
                            CategoryId = 1,
                            CoverImageUrl = "/images/book1.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 450m,
                            Title = "Маленький принц"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джордж Оруэлл",
                            CategoryId = 2,
                            CoverImageUrl = "/images/book2.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 550m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джейн Остин",
                            CategoryId = 4,
                            CoverImageUrl = "/images/book3.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 600m,
                            Title = "Гордость и предубеждение"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Михаил Шолохов",
                            CategoryId = 1,
                            CoverImageUrl = "/images/book4.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 700m,
                            Title = "Тихий Дон"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Михаил Булгаков",
                            CategoryId = 1,
                            CoverImageUrl = "/images/book5.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 650m,
                            Title = "Мастер и Маргарита"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Дж. К. Роулинг",
                            CategoryId = 3,
                            CoverImageUrl = "/images/book6.jpg",
                            IsNew = false,
                            IsPopular = true,
                            Price = 500m,
                            Title = "Гарри Поттер и Философский камень"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Художественная литература"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Детективы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Детская литература"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Бизнес и саморазвитие"
                        },
                        new
                        {
                            Id = 7,
                            Name = "История"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Наука и техника"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Психология"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Кулинария"
                        });
                });

            modelBuilder.Entity("QuanLySach.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLySach.Models.Book", b =>
                {
                    b.HasOne("QuanLySach.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuanLySach.Models.CartItem", b =>
                {
                    b.HasOne("QuanLySach.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QuanLySach.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
